name: iac
description: IAC provionsiong tools including terraform, awscli, kubectl, helm, etc
inputs:
  workdir:
    default: .
  envfile:
    default: .env
  envblock:
    default: null
  command:
    required: true
outputs:
  output:
    description: Output from command
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.workdir }}
    - ${{ inputs.envfile }}
    - ${{ inputs.envblock }}
    - ${{ inputs.command }}

